resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;
resolver_timeout 5s;

acme_client letsencrypt https://acme-v02.api.letsencrypt.org/directory;

server {
    listen 80 default_server;
    server_name _;
    root /etc/angie/web/boxctl;
    location / {
        try_files /index.html =444;
    }
}
