map $http_cf_connecting_ip $real_client_ip {
    default $http_cf_connecting_ip;
    ""      $remote_addr;
}

acme_client letsencrypt https://acme-v02.api.letsencrypt.org/directory;

server {
    listen 80 default_server;
    server_name _;
    root /etc/angie/html/boxctl;
    location / {
        try_files /index.html =444;
    }
}
